---
development:
  cloud_name: doy8fkmkm
  api_key: '639111213674279'
  api_secret: ktOK2KBzuooqYfLnvRaHuIq7MLc
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: doy8fkmkm
  api_key: '639111213674279'
  api_secret: ktOK2KBzuooqYfLnvRaHuIq7MLc
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: doy8fkmkm
  api_key: '639111213674279'
  api_secret: ktOK2KBzuooqYfLnvRaHuIq7MLc
  enhance_image_tag: true
  static_file_support: false
